# repos:
#   - repo: local
#     hooks:
#       - id: trufflehog
#         name: TruffleHog
#         description: Scan for secrets using TruffleHog
#         entry: bash -c 'trufflehog git file://. --since-commit HEAD --fail --no-update --regex --entropy --config=.trufflehog.yml'
#         language: system
#         pass_filenames: false
#         stages: [pre-commit, pre-push]


repos:
  - repo: local
    hooks:
      - id: setup-gitleaks
        name: Setup Gitleaks
        entry: ./setup-gitleaks.sh
        language: system
        always_run: true
        pass_filenames: false
        stages: [pre-commit]
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.24.2
    hooks:
      - id: gitleaks