name: Gitleaks Secret Scanning

on:
  push:
    branches: [main] # or your protected branch
  pull_request:
    branches: [main]

permissions:
  contents: read
  security-events: write # 👈 Required to upload SARIF

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        with:
          args: detect --source=. --report-format=sarif --report-path=gitleaks.sarif

      - name: Upload SARIF file to GitHub
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: gitleaks.sarif
